name: Deploy DApp to Cloudflare with GH Actions

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Run a build step here if your project requires
      - name: Install dependencies
        run: npm install
      - name: Build DApp
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID}}
          projectName: dapp-cloudflare-gh-actions
          directory: build

