name: Deploy DApp to Cloudflare with GH Actions

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a build step here if your project requires
      - name: Install dependencies
        run: npm install
        
      - name: updating
        run: npm update --latest react-scripts
        
      - name: Build DApp
        run: |
         npm run build --if-present
         # echo "Build successfull"

      - name: Publish to Cloudflare Pages
        # run: |
        # echo "Published"
        uses: cloudflare/pages-action@v1
        with:
         apiToken: ${{ secrets.CF_API_TOKEN }}
         accountId: ${{ secrets.CF_ACCOUNT_ID}}
         projectName: dapp-cloudflare-gh-actions
         directory: ./build
         gitHubToken: ${{ secrets.GITUB_TOKEN }}
        id: publish
      - name: Outputs
        run: |
          echo "ID: ${{ steps.publish.outputs.id }}"
          echo "URL: ${{ steps.publish.outputs.url }}"
          echo "Environment: ${{ steps.publish.outputs.environment }}"
          echo "Alias: ${{ steps.publish.outputs.alias }}"

