name: Deploy DApp to Cloudflare with GH Actions
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Compile contracts
      run: npx truffle compile

    - name: Migrate contracts
      run: npx truffle migrate --network <network-name>

    - name: Build DApp
      run: npm run build

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@3.14.1
      with:
        build_dir: build
        site_id: ${{ secrets.CF_ACCOUNT_ID}}
        api_token: ${{ secrets.CF_API_TOKEN }}
